from aqt.qt import *

class GeneralTabMixin:
    def _create_general_tab(self):
        """Constructs the Tab 1: General Settings UI"""
        self.general_tab = QWidget()
        
        scroll_area = QScrollArea()
        scroll_area.setWidgetResizable(True)
        if hasattr(QFrame, "Shape"):
            scroll_area.setFrameShape(QFrame.Shape.NoFrame)
        else:
            scroll_area.setFrameShape(QFrame.NoFrame)
        
        scroll_content = QWidget()
        gen_layout = QFormLayout()
        
        self.ai_provider_cb = QComboBox()
        self.ai_provider_cb.setToolTip("Select the main AI model provider for generating hints.")
        gen_layout.addRow("Active AI Provider:", self.ai_provider_cb)
        
        self.options_count_sb = QSpinBox()
        self.options_count_sb.setRange(1, 10)
        self.options_count_sb.setToolTip("Set how many multiple-choice options (answers) the AI should generate per card.")
        gen_layout.addRow("Number of Options:", self.options_count_sb)
        
        self.mathjax_format_cb = QComboBox()
        self.mathjax_format_cb.addItems(["delimiters", "inline"])
        self.mathjax_format_cb.setToolTip(r"delimiters: \( ... \), \[ ... \]. inline: $ ... $, $$ ... $")
        gen_layout.addRow("MathJax Format:", self.mathjax_format_cb)

        self.answer_display_position_cb = QComboBox()
        self.answer_display_position_cb.addItems(["between", "bottom"])
        self.answer_display_position_cb.setToolTip("Select where AI hints/options are shown on the answer side:\nbetween: Front, AI Data, Back (default)\nbottom: Front, Back, AI Data")
        gen_layout.addRow("Answer Display Position:", self.answer_display_position_cb)
        
        self.fix_latex_cb = QCheckBox("Repair AI LaTeX Errors")
        self.fix_latex_cb.setToolTip("Automatically fix common AI math errors like missing backslashes or missing delimiters.")
        gen_layout.addRow(self.fix_latex_cb)

        # --- Button Visibility Group ---
        button_group = QGroupBox("Button Visibility")
        button_layout = QFormLayout()
        
        self.show_hints_cb = QCheckBox("Show Hints Button")
        self.show_hints_cb.setToolTip("Render the foldable 'Hints' section container on the review screen.")
        button_layout.addRow(self.show_hints_cb)
        
        self.show_options_cb = QCheckBox("Show Options Button (Sequential)")
        self.show_options_cb.setToolTip("Render the clickable 'Options' section container on the review screen.")
        button_layout.addRow(self.show_options_cb)
        
        self.show_on_card_cb = QCheckBox("Show Generate Button on Review Card")
        self.show_on_card_cb.setToolTip("Embed generation controls (Generate, Regenerate, Clear) inline inside the card itself.")
        button_layout.addRow(self.show_on_card_cb)
        
        button_group.setLayout(button_layout)
        
        # --- Auto-Show & Generation Group ---
        show_group = QGroupBox("Auto-Show & Generation")
        show_layout = QFormLayout()

        self.auto_generate_new_cb = QCheckBox("Auto Generate for New Cards")
        self.auto_generate_new_cb.setToolTip("Automatically run AI generation for new/empty cards that do not have hints/options yet.")
        show_layout.addRow(self.auto_generate_new_cb)

        self.auto_regenerate_all_cb = QCheckBox("└─ Force Regenerate Even if Data Exists")
        self.auto_regenerate_all_cb.setToolTip("Always overwrite hints, even for cards that already have data. Requires primary Auto-Generate to be active.")
        self.auto_regenerate_all_cb.setStyleSheet("margin-left: 15px;")
        show_layout.addRow(self.auto_regenerate_all_cb)

        self.auto_regenerate_old_version_cb = QCheckBox("└─ Regenerate if Generated Version < ")
        self.auto_regenerate_old_version_cb.setToolTip(
            "Automatically regenerate hints for cards whose stored version is older than the version number you specify. "
            "Requires Auto Generate to be active. Leave the version field empty to disable."
        )
        self.auto_regenerate_old_version_cb.setStyleSheet("margin-left: 15px;")
        self.auto_regenerate_min_version_edit = QLineEdit()
        self.auto_regenerate_min_version_edit.setPlaceholderText("e.g. 1.4.2")
        self.auto_regenerate_min_version_edit.setFixedWidth(80)
        self.auto_regenerate_min_version_edit.setToolTip(
            "Cards generated by an addon version older than this will be regenerated automatically."
        )
        version_container = QWidget()
        version_row = QHBoxLayout(version_container)
        version_row.setContentsMargins(15, 0, 0, 0)
        version_row.setSpacing(5)
        version_row.addWidget(self.auto_regenerate_old_version_cb)
        version_row.addWidget(self.auto_regenerate_min_version_edit)
        version_row.addStretch()
        show_layout.addRow(version_container)

        self.auto_regenerate_old_time_cb = QCheckBox("└─ Regenerate if Generated Time < ")
        self.auto_regenerate_old_time_cb.setToolTip(
            "Automatically regenerate hints for cards whose stored generation time is older than the time you specify. "
            "Requires Auto Generate to be active. Format: YYYY-MM-DD or YYYY-MM-DD HH:MM:SS. Leave empty or uncheck to disable."
        )
        self.auto_regenerate_old_time_cb.setStyleSheet("margin-left: 15px;")
        self.auto_regenerate_min_time_edit = QLineEdit()
        self.auto_regenerate_min_time_edit.setPlaceholderText("e.g. 2026-06-06")
        self.auto_regenerate_min_time_edit.setFixedWidth(120)
        self.auto_regenerate_min_time_edit.setToolTip(
            "Cards generated before this date/time will be regenerated automatically. Format: YYYY-MM-DD [HH:MM:SS]. Leave empty to disable."
        )
        time_container = QWidget()
        time_row = QHBoxLayout(time_container)
        time_row.setContentsMargins(15, 0, 0, 0)
        time_row.setSpacing(5)
        time_row.addWidget(self.auto_regenerate_old_time_cb)
        time_row.addWidget(self.auto_regenerate_min_time_edit)
        time_row.addStretch()
        show_layout.addRow(time_container)

        self.auto_regenerate_if_modified_cb = QCheckBox("└─ Regenerate if Card Modified > Generated Date")
        self.auto_regenerate_if_modified_cb.setToolTip(
            "Automatically regenerate hints/options if the card/note modified date is newer than the AI data generation timestamp. "
            "Requires Auto Generate to be active."
        )
        self.auto_regenerate_if_modified_cb.setStyleSheet("margin-left: 15px;")
        show_layout.addRow(self.auto_regenerate_if_modified_cb)

        pregen_container = QWidget()
        pregen_row = QHBoxLayout(pregen_container)
        pregen_row.setContentsMargins(0, 0, 0, 0)
        pregen_row.setSpacing(10)

        self.pre_generate_next_cb = QCheckBox("Pre-generate ahead")
        self.pre_generate_next_cb.setToolTip(
            "Start generating hints for upcoming cards in the queue in the background while you are reviewing the current one."
        )
        pregen_row.addWidget(self.pre_generate_next_cb)

        pregen_row.addWidget(QLabel("Buffer size:"))
        self.pre_generate_count_spin = QSpinBox()
        self.pre_generate_count_spin.setRange(1, 10)
        self.pre_generate_count_spin.setFixedWidth(50)
        self.pre_generate_count_spin.setToolTip("How many upcoming cards to pregenerate and keep in the cache (default is 3).")
        pregen_row.addWidget(self.pre_generate_count_spin)
        pregen_row.addStretch()
        show_layout.addRow(pregen_container)

        # Couple all sub-checkboxes to the primary Auto-Generate checkbox
        def _update_regen_controls(enabled):
            self.auto_regenerate_all_cb.setEnabled(enabled)
            self.auto_regenerate_if_modified_cb.setEnabled(enabled)
            self.auto_regenerate_old_version_cb.setEnabled(enabled)
            self.auto_regenerate_min_version_edit.setEnabled(
                enabled and self.auto_regenerate_old_version_cb.isChecked()
            )
            self.auto_regenerate_old_time_cb.setEnabled(enabled)
            self.auto_regenerate_min_time_edit.setEnabled(
                enabled and self.auto_regenerate_old_time_cb.isChecked()
            )
            self.pre_generate_next_cb.setEnabled(enabled)
            self.pre_generate_count_spin.setEnabled(enabled and self.pre_generate_next_cb.isChecked())
            if not enabled:
                self.pre_generate_next_cb.setChecked(False)

        self.auto_generate_new_cb.toggled.connect(_update_regen_controls)
        self.pre_generate_next_cb.toggled.connect(
            lambda checked: self.pre_generate_count_spin.setEnabled(
                checked and self.auto_generate_new_cb.isChecked()
            )
        )
        self.auto_regenerate_old_version_cb.toggled.connect(
            lambda checked: self.auto_regenerate_min_version_edit.setEnabled(
                checked and self.auto_generate_new_cb.isChecked()
            )
        )
        self.auto_regenerate_old_time_cb.toggled.connect(
            lambda checked: self.auto_regenerate_min_time_edit.setEnabled(
                checked and self.auto_generate_new_cb.isChecked()
            )
        )

        show_layout.addRow(QLabel("<b>On Card Load:</b>"))
        self.auto_show_hints_cb = QCheckBox("Auto Show Hints")
        self.auto_show_hints_cb.setToolTip("Automatically expand and show hints when a card is loaded.")
        show_layout.addRow(self.auto_show_hints_cb)

        self.auto_show_options_cb = QCheckBox("Auto Show Options")
        self.auto_show_options_cb.setToolTip("Automatically expand and show options when a card is loaded.")
        show_layout.addRow(self.auto_show_options_cb)

        self.do_not_auto_collapse_cb = QCheckBox("Do Not Auto-Collapse on Next Card")
        self.do_not_auto_collapse_cb.setToolTip("Remember the expanded/collapsed state of hints and options when moving to the next card.")
        show_layout.addRow(self.do_not_auto_collapse_cb)

        # Correct Answer rating settings layout
        rate_good_container = QWidget()
        rate_good_row = QHBoxLayout(rate_good_container)
        rate_good_row.setContentsMargins(0, 0, 0, 0)
        rate_good_row.setSpacing(5)
        self.rate_good_on_correct_cb = QCheckBox("Auto Rate Good on Correct Option")
        self.rate_good_on_correct_cb.setToolTip("If you click the correct option on the front/question side of the card, automatically answer 'Good'.")
        rate_good_row.addWidget(self.rate_good_on_correct_cb)
        
        self.rate_good_delay_lbl = QLabel("Delay:")
        rate_good_row.addWidget(self.rate_good_delay_lbl)
        self.rate_good_delay_spin = QDoubleSpinBox()
        self.rate_good_delay_spin.setRange(0.0, 10.0)
        self.rate_good_delay_spin.setSingleStep(0.5)
        self.rate_good_delay_spin.setValue(0.0)
        self.rate_good_delay_spin.setSuffix("s")
        self.rate_good_delay_spin.setToolTip("Delay (in seconds) before rating 'Good' (0.0s is instant).")
        rate_good_row.addWidget(self.rate_good_delay_spin)
        rate_good_row.addStretch()
        show_layout.addRow(rate_good_container)

        # Wrong Answer rating settings layout
        rate_again_container = QWidget()
        rate_again_row = QHBoxLayout(rate_again_container)
        rate_again_row.setContentsMargins(0, 0, 0, 0)
        rate_again_row.setSpacing(5)
        self.rate_again_on_wrong_cb = QCheckBox("Auto Rate Again on Wrong Option")
        self.rate_again_on_wrong_cb.setToolTip("If you click a wrong option on the front/question side of the card, reveal correct answer, highlight wrong selection in red, and rate 'Again'.")
        rate_again_row.addWidget(self.rate_again_on_wrong_cb)
        
        self.rate_again_delay_lbl = QLabel("Delay:")
        rate_again_row.addWidget(self.rate_again_delay_lbl)
        self.rate_again_delay_spin = QDoubleSpinBox()
        self.rate_again_delay_spin.setRange(0.0, 10.0)
        self.rate_again_delay_spin.setSingleStep(0.5)
        self.rate_again_delay_spin.setValue(1.0)
        self.rate_again_delay_spin.setSuffix("s")
        self.rate_again_delay_spin.setToolTip("Delay (in seconds) before rating 'Again' (e.g. 1.0s to view colors first).")
        rate_again_row.addWidget(self.rate_again_delay_spin)
        rate_again_row.addStretch()
        show_layout.addRow(rate_again_container)

        # Connect toggles to enable/disable delay spin boxes
        self.rate_good_on_correct_cb.toggled.connect(self.rate_good_delay_spin.setEnabled)
        self.rate_again_on_wrong_cb.toggled.connect(self.rate_again_delay_spin.setEnabled)

        show_layout.addRow(QLabel("<b>Note Tagging:</b>"))

        # Tag hinted notes
        tag_hinted_container = QWidget()
        tag_hinted_row = QHBoxLayout(tag_hinted_container)
        tag_hinted_row.setContentsMargins(0, 0, 0, 0)
        tag_hinted_row.setSpacing(5)
        self.tag_hinted_notes_cb = QCheckBox("Tag Notes with AI Hints")
        self.tag_hinted_notes_cb.setToolTip(
            "Automatically add a tag (default: 'ai-hints') to notes when hints are generated, "
            "and remove it when hints are cleared. Useful for filtering in the Browser."
        )
        tag_hinted_row.addWidget(self.tag_hinted_notes_cb)

        self.hint_tag_edit = QLineEdit()
        self.hint_tag_edit.setPlaceholderText("ai-hints")
        self.hint_tag_edit.setMaximumWidth(160)
        self.hint_tag_edit.setToolTip("Tag name to apply to notes that have AI hints.")
        tag_hinted_row.addWidget(self.hint_tag_edit)
        tag_hinted_row.addStretch()
        show_layout.addRow(tag_hinted_container)

        # Tag skipped notes
        tag_skipped_container = QWidget()
        tag_skipped_row = QHBoxLayout(tag_skipped_container)
        tag_skipped_row.setContentsMargins(0, 0, 0, 0)
        tag_skipped_row.setSpacing(5)
        self.tag_skipped_notes_cb = QCheckBox("Tag Skipped Notes")
        self.tag_skipped_notes_cb.setToolTip(
            "Automatically add a tag (default: 'ai-hints::skipped') to notes when AI is skipped, "
            "and remove it when unskipped. Helps identify skipped cards in the Browser."
        )
        tag_skipped_row.addWidget(self.tag_skipped_notes_cb)

        self.skip_tag_edit = QLineEdit()
        self.skip_tag_edit.setPlaceholderText("ai-hints::skipped")
        self.skip_tag_edit.setMaximumWidth(160)
        self.skip_tag_edit.setToolTip("Tag name to apply to notes that are marked as skipped.")
        tag_skipped_row.addWidget(self.skip_tag_edit)
        tag_skipped_row.addStretch()
        show_layout.addRow(tag_skipped_container)

        # Enable/disable tag edit fields based on checkbox state
        self.tag_hinted_notes_cb.toggled.connect(self.hint_tag_edit.setEnabled)
        self.tag_skipped_notes_cb.toggled.connect(self.skip_tag_edit.setEnabled)

        show_layout.addRow(QLabel("<b>After Manual Generation:</b>"))
        self.manual_show_hints_cb = QCheckBox("Auto Show Hints")
        self.manual_show_hints_cb.setToolTip("Automatically expand and show hints after clicking Generate/Regenerate.")
        show_layout.addRow(self.manual_show_hints_cb)

        self.manual_show_options_cb = QCheckBox("Auto Show Options")
        self.manual_show_options_cb.setToolTip("Automatically expand and show options after clicking Generate/Regenerate.")
        show_layout.addRow(self.manual_show_options_cb)
        
        show_group.setLayout(show_layout)
        
        # Main layout wrapper to prevent vertical stretching
        main_layout = QVBoxLayout()
        main_layout.addLayout(gen_layout)
        main_layout.addWidget(button_group)
        main_layout.addWidget(show_group)
        main_layout.addStretch()
        
        scroll_content.setLayout(main_layout)
        scroll_area.setWidget(scroll_content)
        
        tab_layout = QVBoxLayout()
        tab_layout.setContentsMargins(0, 0, 0, 0)
        tab_layout.addWidget(scroll_area)
        
        self.general_tab.setLayout(tab_layout)
        return self.general_tab
