from aqt.qt import *

class GeneralTabMixin:
    def _create_general_tab(self):
        """Constructs the Tab 1: General Settings UI"""
        self.general_tab = QWidget()
        
        scroll_area = QScrollArea()
        scroll_area.setWidgetResizable(True)
        if hasattr(QFrame, "Shape"):
            scroll_area.setFrameShape(QFrame.Shape.NoFrame)
        else:
            scroll_area.setFrameShape(QFrame.NoFrame)
        
        scroll_content = QWidget()
        gen_layout = QFormLayout()
        
        self.ai_provider_cb = QComboBox()
        self.ai_provider_cb.setToolTip("Select the main AI model provider for generating hints.")
        gen_layout.addRow("Active AI Provider:", self.ai_provider_cb)
        
        self.options_count_sb = QSpinBox()
        self.options_count_sb.setRange(1, 10)
        self.options_count_sb.setToolTip("Set how many multiple-choice options (answers) the AI should generate per card.")
        gen_layout.addRow("Number of Options:", self.options_count_sb)
        
        self.mathjax_format_cb = QComboBox()
        self.mathjax_format_cb.addItems(["delimiters", "inline"])
        self.mathjax_format_cb.setToolTip(r"delimiters: \( ... \), \[ ... \]. inline: $ ... $, $$ ... $")
        gen_layout.addRow("MathJax Format:", self.mathjax_format_cb)

        self.answer_display_position_cb = QComboBox()
        self.answer_display_position_cb.addItems(["between", "bottom"])
        self.answer_display_position_cb.setToolTip("Select where AI hints/options are shown on the answer side:\nbetween: Front, AI Data, Back (default)\nbottom: Front, Back, AI Data")
        gen_layout.addRow("Answer Display Position:", self.answer_display_position_cb)
        
        self.fix_latex_cb = QCheckBox("Repair AI LaTeX Errors")
        self.fix_latex_cb.setToolTip("Automatically fix common AI math errors like missing backslashes or missing delimiters.")
        gen_layout.addRow(self.fix_latex_cb)

        # --- Button Visibility Group ---
        button_group = QGroupBox("Button Visibility")
        button_layout = QFormLayout()
        
        self.show_hints_cb = QCheckBox("Show Hints Button")
        self.show_hints_cb.setToolTip("Render the foldable 'Hints' section container on the review screen.")
        button_layout.addRow(self.show_hints_cb)
        
        self.show_options_cb = QCheckBox("Show Options Button (Sequential)")
        self.show_options_cb.setToolTip("Render the clickable 'Options' section container on the review screen.")
        button_layout.addRow(self.show_options_cb)
        
        self.show_on_card_cb = QCheckBox("Show Generate Button on Review Card")
        self.show_on_card_cb.setToolTip("Embed generation controls (Generate, Regenerate, Clear) inline inside the card itself.")
        button_layout.addRow(self.show_on_card_cb)
        
        self.show_in_bottom_bar_cb = QCheckBox("Show Generate Button in Review Bar")
        self.show_in_bottom_bar_cb.setToolTip("Place generation controls at the very bottom of the reviewer, next to answer buttons.")
        button_layout.addRow(self.show_in_bottom_bar_cb)

        self.show_in_popup_cb = QCheckBox("Show Results in Popup Window")
        self.show_in_popup_cb.setToolTip("Open successful generations in a non-blocking popup window for review before storing.")
        button_layout.addRow(self.show_in_popup_cb)
        
        button_group.setLayout(button_layout)
        
        # --- Auto-Show & Generation Group ---
        show_group = QGroupBox("Auto-Show & Generation")
        show_layout = QFormLayout()

        self.auto_generate_new_cb = QCheckBox("Auto Generate for New Cards")
        self.auto_generate_new_cb.setToolTip("Automatically run AI generation for new/empty cards that do not have hints/options yet.")
        show_layout.addRow(self.auto_generate_new_cb)

        self.auto_regenerate_all_cb = QCheckBox("└─ Force Regenerate Even if Data Exists")
        self.auto_regenerate_all_cb.setToolTip("Always overwrite hints, even for cards that already have data. Requires primary Auto-Generate to be active.")
        self.auto_regenerate_all_cb.setStyleSheet("margin-left: 15px;")
        show_layout.addRow(self.auto_regenerate_all_cb)

        self.auto_regenerate_old_version_cb = QCheckBox("└─ Regenerate if Generated Version < ")
        self.auto_regenerate_old_version_cb.setToolTip(
            "Automatically regenerate hints for cards whose stored version is older than the version number you specify. "
            "Requires Auto Generate to be active. Leave the version field empty to disable."
        )
        self.auto_regenerate_old_version_cb.setStyleSheet("margin-left: 15px;")
        self.auto_regenerate_min_version_edit = QLineEdit()
        self.auto_regenerate_min_version_edit.setPlaceholderText("e.g. 1.4.2")
        self.auto_regenerate_min_version_edit.setFixedWidth(80)
        self.auto_regenerate_min_version_edit.setToolTip(
            "Cards generated by an addon version older than this will be regenerated automatically."
        )
        version_container = QWidget()
        version_row = QHBoxLayout(version_container)
        version_row.setContentsMargins(15, 0, 0, 0)
        version_row.setSpacing(5)
        version_row.addWidget(self.auto_regenerate_old_version_cb)
        version_row.addWidget(self.auto_regenerate_min_version_edit)
        version_row.addStretch()
        show_layout.addRow(version_container)

        self.auto_regenerate_old_time_cb = QCheckBox("└─ Regenerate if Generated Time < ")
        self.auto_regenerate_old_time_cb.setToolTip(
            "Automatically regenerate hints for cards whose stored generation time is older than the time you specify. "
            "Requires Auto Generate to be active. Format: YYYY-MM-DD or YYYY-MM-DD HH:MM:SS. Leave empty or uncheck to disable."
        )
        self.auto_regenerate_old_time_cb.setStyleSheet("margin-left: 15px;")
        self.auto_regenerate_min_time_edit = QLineEdit()
        self.auto_regenerate_min_time_edit.setPlaceholderText("e.g. 2026-06-06")
        self.auto_regenerate_min_time_edit.setFixedWidth(120)
        self.auto_regenerate_min_time_edit.setToolTip(
            "Cards generated before this date/time will be regenerated automatically. Format: YYYY-MM-DD [HH:MM:SS]. Leave empty to disable."
        )
        time_container = QWidget()
        time_row = QHBoxLayout(time_container)
        time_row.setContentsMargins(15, 0, 0, 0)
        time_row.setSpacing(5)
        time_row.addWidget(self.auto_regenerate_old_time_cb)
        time_row.addWidget(self.auto_regenerate_min_time_edit)
        time_row.addStretch()
        show_layout.addRow(time_container)

        pregen_container = QWidget()
        pregen_row = QHBoxLayout(pregen_container)
        pregen_row.setContentsMargins(0, 0, 0, 0)
        pregen_row.setSpacing(10)

        self.pre_generate_next_cb = QCheckBox("Pre-generate ahead")
        self.pre_generate_next_cb.setToolTip(
            "Start generating hints for upcoming cards in the queue in the background while you are reviewing the current one."
        )
        pregen_row.addWidget(self.pre_generate_next_cb)

        pregen_row.addWidget(QLabel("Buffer size:"))
        self.pre_generate_count_spin = QSpinBox()
        self.pre_generate_count_spin.setRange(1, 10)
        self.pre_generate_count_spin.setFixedWidth(50)
        self.pre_generate_count_spin.setToolTip("How many upcoming cards to pregenerate and keep in the cache (default is 3).")
        pregen_row.addWidget(self.pre_generate_count_spin)
        pregen_row.addStretch()
        show_layout.addRow(pregen_container)

        # Couple all sub-checkboxes to the primary Auto-Generate checkbox
        def _update_regen_controls(enabled):
            self.auto_regenerate_all_cb.setEnabled(enabled)
            self.auto_regenerate_old_version_cb.setEnabled(enabled)
            self.auto_regenerate_min_version_edit.setEnabled(
                enabled and self.auto_regenerate_old_version_cb.isChecked()
            )
            self.auto_regenerate_old_time_cb.setEnabled(enabled)
            self.auto_regenerate_min_time_edit.setEnabled(
                enabled and self.auto_regenerate_old_time_cb.isChecked()
            )
            self.pre_generate_next_cb.setEnabled(enabled)
            self.pre_generate_count_spin.setEnabled(enabled and self.pre_generate_next_cb.isChecked())
            if not enabled:
                self.pre_generate_next_cb.setChecked(False)

        self.auto_generate_new_cb.toggled.connect(_update_regen_controls)
        self.pre_generate_next_cb.toggled.connect(
            lambda checked: self.pre_generate_count_spin.setEnabled(
                checked and self.auto_generate_new_cb.isChecked()
            )
        )
        self.auto_regenerate_old_version_cb.toggled.connect(
            lambda checked: self.auto_regenerate_min_version_edit.setEnabled(
                checked and self.auto_generate_new_cb.isChecked()
            )
        )
        self.auto_regenerate_old_time_cb.toggled.connect(
            lambda checked: self.auto_regenerate_min_time_edit.setEnabled(
                checked and self.auto_generate_new_cb.isChecked()
            )
        )

        show_layout.addRow(QLabel("<b>On Card Load:</b>"))
        self.auto_show_hints_cb = QCheckBox("Auto Show Hints")
        self.auto_show_hints_cb.setToolTip("Automatically expand and show hints when a card is loaded.")
        show_layout.addRow(self.auto_show_hints_cb)

        self.auto_show_options_cb = QCheckBox("Auto Show Options")
        self.auto_show_options_cb.setToolTip("Automatically expand and show options when a card is loaded.")
        show_layout.addRow(self.auto_show_options_cb)

        self.do_not_auto_collapse_cb = QCheckBox("Do Not Auto-Collapse on Next Card")
        self.do_not_auto_collapse_cb.setToolTip("Remember the expanded/collapsed state of hints and options when moving to the next card.")
        show_layout.addRow(self.do_not_auto_collapse_cb)

        show_layout.addRow(QLabel("<b>After Manual Generation:</b>"))
        self.manual_show_hints_cb = QCheckBox("Auto Show Hints")
        self.manual_show_hints_cb.setToolTip("Automatically expand and show hints after clicking Generate/Regenerate.")
        show_layout.addRow(self.manual_show_hints_cb)

        self.manual_show_options_cb = QCheckBox("Auto Show Options")
        self.manual_show_options_cb.setToolTip("Automatically expand and show options after clicking Generate/Regenerate.")
        show_layout.addRow(self.manual_show_options_cb)
        
        show_group.setLayout(show_layout)
        
        # Main layout wrapper to prevent vertical stretching
        main_layout = QVBoxLayout()
        main_layout.addLayout(gen_layout)
        main_layout.addWidget(button_group)
        main_layout.addWidget(show_group)
        main_layout.addStretch()
        
        scroll_content.setLayout(main_layout)
        scroll_area.setWidget(scroll_content)
        
        tab_layout = QVBoxLayout()
        tab_layout.setContentsMargins(0, 0, 0, 0)
        tab_layout.addWidget(scroll_area)
        
        self.general_tab.setLayout(tab_layout)
        return self.general_tab
