import re
import json
import html
from typing import List, Optional, Tuple, Dict

class CardParser:
    _MATH_BLOCK_RE = re.compile(
        r'(\\\(.*?\\\)|\\\[.*?\\\]|<anki-mathjax\b[^>]*>.*?</anki-mathjax>)',
        flags=re.DOTALL | re.IGNORECASE,
    )

    def __init__(self, target_fields: List[str], note_type_fields: Dict[str, List[str]] = None, storage_mode: str = "json", mathjax_format: str = "delimiters"):
        self.target_fields = target_fields
        self.note_type_fields = note_type_fields or {}
        self.storage_mode = storage_mode
        self.mathjax_format = mathjax_format
        self.container_class = "ai-hints-container"
        self.json_class = "ai-hints-json"

    def _fix_lazy_latex(self, text: str) -> str:
        """Repairs common AI math errors like missing backslashes or joined commands."""
        if not isinstance(text, str):
            return text

        return self._normalize_math_text(text)

    def normalize_hint_data(self, data: Dict[str, List[str]]) -> Dict[str, List[str]]:
        """Normalize generated hint text before storage or direct reviewer injection."""
        normalized = {"hints": [], "options": []}
        if not isinstance(data, dict):
            return normalized

        for key in ("hints", "options"):
            values = data.get(key, [])
            if not isinstance(values, list):
                values = [values]
            for value in values:
                text = self._normalize_math_text(str(value))
                if self.mathjax_format == "tags":
                    text = self._convert_to_mathjax_tags(text)
                normalized[key].append(text)
        return normalized

    def _normalize_math_text(self, text: str) -> str:
        if not isinstance(text, str):
            return text

        text = self._normalize_overescaped_math_delimiters(text)
        text = self._normalize_anki_mathjax_tags(text)
        text = self._normalize_dollar_math_delimiters(text)
        text = self._normalize_mixed_math_delimiters(text)
        
        # Standardize delimiters and fix inner LaTeX.
        # This deduplicates backslashes (e.g., \\( -> \( ) frequently generated by over-zealous AIs
        # or double-serialization issues.
        text = re.sub(
            r'\\+[\(\[](.*?)\\+[\)\]]',
            lambda m: (r'\(' if '(' in m.group(0) or '[' not in m.group(0) else r'\[') 
                      + self._fix_latex_span(m.group(1)) 
                      + (r'\)' if ')' in m.group(0) or ']' not in m.group(0) else r'\]'),
            text,
            flags=re.DOTALL,
        )

        if "<anki-mathjax" not in text.lower():
            if self._should_wrap_standalone_math(text):
                text = r'\(' + self._fix_latex_span(text.strip()) + r'\)'
            else:
                text = self._wrap_parenthetical_math(text)
                text = self._wrap_bare_math_tokens(text)

        return text

    def _normalize_overescaped_math_delimiters(self, text: str) -> str:
        return re.sub(r'\\\\([()\[\]])', lambda m: "\\" + m.group(1), text)

    def _normalize_anki_mathjax_tags(self, text: str) -> str:
        return re.sub(
            r'(<anki-mathjax\b[^>]*>)(.*?)(</anki-mathjax>)',
            lambda m: m.group(1) + self._fix_latex_span(m.group(2)) + m.group(3),
            text,
            flags=re.DOTALL | re.IGNORECASE,
        )

    def _math_block_ranges(self, text: str) -> List[Tuple[int, int]]:
        return [match.span() for match in self._MATH_BLOCK_RE.finditer(text)]

    def _index_in_ranges(self, index: int, ranges: List[Tuple[int, int]]) -> bool:
        return any(start <= index < end for start, end in ranges)

    def _normalize_dollar_math_delimiters(self, text: str) -> str:
        def convert_display(match):
            inner = match.group(1)
            if self._looks_like_math_span(inner):
                return r'\[' + self._fix_latex_span(inner) + r'\]'
            return match.group(0)

        def convert_inline(match):
            inner = match.group(1)
            if self._looks_like_math_span(inner):
                return r'\(' + self._fix_latex_span(inner) + r'\)'
            return match.group(0)

        text = re.sub(
            r'(?<!\\)\$\$(.*?)(?<!\\)\$\$',
            convert_display,
            text,
            flags=re.DOTALL,
        )
        return re.sub(
            r'(?<!\\)\$(?!\$)([^\n$]{1,220})(?<!\\)\$(?!\$)',
            convert_inline,
            text,
        )

    def _normalize_mixed_math_delimiters(self, text: str) -> str:
        protected = self._math_block_ranges(text)
        text = self._normalize_plain_display_open_escaped_close(text, protected)
        protected = self._math_block_ranges(text)
        text = self._normalize_plain_open_escaped_close(text, protected)
        text = self._normalize_escaped_display_open_plain_close(text)
        return self._normalize_escaped_open_plain_close(text)

    def _normalize_plain_display_open_escaped_close(self, text: str, protected_ranges: List[Tuple[int, int]] = None) -> str:
        protected_ranges = protected_ranges or []
        result = []
        i = 0
        while i < len(text):
            if (
                text[i] != "["
                or self._is_escaped(text, i)
                or self._index_in_ranges(i, protected_ranges)
            ):
                result.append(text[i])
                i += 1
                continue

            if i > 0 and re.match(r'[A-Za-z0-9]', text[i - 1]):
                result.append(text[i])
                i += 1
                continue

            close = self._find_next_escaped_display_close(text, i + 1)
            if close == -1:
                result.append(text[i])
                i += 1
                continue

            inner = text[i + 1:close]
            if self._looks_like_math_span(self._unwrap_math_delimiters_inside_span(inner)):
                result.append(r'\[')
                result.append(self._fix_latex_span(inner))
                result.append(r'\]')
                i = close + 2
            else:
                result.append(text[i])
                i += 1
        return "".join(result)

    def _normalize_escaped_display_open_plain_close(self, text: str) -> str:
        result = []
        i = 0
        while i < len(text):
            if not text.startswith(r'\[', i):
                result.append(text[i])
                i += 1
                continue

            if self._find_next_escaped_display_close(text, i + 2) != -1:
                result.append(r'\[')
                i += 2
                continue

            close = self._find_next_unescaped_close_bracket(text, i + 2)
            if close == -1:
                result.append(text[i])
                i += 1
                continue

            inner = text[i + 2:close]
            if self._looks_like_math_span(self._unwrap_math_delimiters_inside_span(inner)):
                result.append(r'\[')
                result.append(self._fix_latex_span(inner))
                result.append(r'\]')
                i = close + 1
            else:
                result.append(text[i])
                i += 1
        return "".join(result)

    def _normalize_plain_open_escaped_close(self, text: str, protected_ranges: List[Tuple[int, int]] = None) -> str:
        protected_ranges = protected_ranges or []
        result = []
        i = 0
        while i < len(text):
            if (
                text[i] != "("
                or self._is_escaped(text, i)
                or self._index_in_ranges(i, protected_ranges)
            ):
                result.append(text[i])
                i += 1
                continue

            if i > 0 and re.match(r'[A-Za-z]', text[i - 1]):
                result.append(text[i])
                i += 1
                continue

            close = self._find_next_escaped_math_close(text, i + 1)
            if close == -1:
                result.append(text[i])
                i += 1
                continue

            inner = text[i + 1:close]
            if self._looks_like_math_span(self._unwrap_math_delimiters_inside_span(inner)):
                result.append(r'\(')
                result.append(self._fix_latex_span(inner))
                result.append(r'\)')
                i = close + 2
            else:
                result.append(text[i])
                i += 1
        return "".join(result)

    def _normalize_escaped_open_plain_close(self, text: str) -> str:
        result = []
        i = 0
        while i < len(text):
            if not text.startswith(r'\(', i):
                result.append(text[i])
                i += 1
                continue

            if self._find_next_escaped_math_close(text, i + 2) != -1:
                result.append(r'\(')
                i += 2
                continue

            close = self._find_next_unescaped_close_paren(text, i + 2)
            if close == -1:
                result.append(text[i])
                i += 1
                continue

            inner = text[i + 2:close]
            if self._looks_like_math_span(self._unwrap_math_delimiters_inside_span(inner)):
                result.append(r'\(')
                result.append(self._fix_latex_span(inner))
                result.append(r'\)')
                i = close + 1
            else:
                result.append(text[i])
                i += 1
        return "".join(result)

    def _find_next_escaped_math_close(self, text: str, start: int) -> int:
        idx = start
        depth = 0
        while idx < len(text) - 1:
            if text.startswith(r'\(', idx):
                depth += 1
                idx += 2
                continue
            if text.startswith(r'\)', idx):
                if depth == 0:
                    return idx
                depth -= 1
                idx += 2
                continue
            idx += 1
        return -1

    def _find_next_escaped_display_close(self, text: str, start: int) -> int:
        idx = start
        depth = 0
        while idx < len(text) - 1:
            if text.startswith(r'\[', idx):
                depth += 1
                idx += 2
                continue
            if text.startswith(r'\]', idx):
                if depth == 0:
                    return idx
                depth -= 1
                idx += 2
                continue
            idx += 1
        return -1

    def _find_next_unescaped_close_paren(self, text: str, start: int) -> int:
        idx = start
        while idx < len(text):
            if text[idx] == ")" and not self._is_escaped(text, idx):
                return idx
            idx += 1
        return -1

    def _find_next_unescaped_close_bracket(self, text: str, start: int) -> int:
        idx = start
        while idx < len(text):
            if text[idx] == "]" and not self._is_escaped(text, idx):
                return idx
            idx += 1
        return -1

    def _is_math_delimiter_escape(self, text: str, index: int) -> bool:
        return index > 0 and text[index] == "\\" and index + 1 < len(text) and text[index + 1] in "()[]"

    def _fix_latex_span(self, span: str) -> str:
        """Repair LaTeX only inside text already identified as math."""
        commands = [
            "exp", "lambda", "frac", "left", "right", "sin", "cos", "tan",
            "sqrt", "log", "ln", "lim", "min", "max", "det", "dim", "ker",
            "approx", "cdot", "times", "div", "pm", "mp", "text", "mathrm",
            "operatorname", "partial", "nabla", "int", "iint", "iiint", "oint",
            "sum", "prod", "infty", "to", "rightarrow", "leftarrow",
            "leftrightarrow", "le", "leq", "ge", "geq", "ne", "neq", "in",
            "notin", "subset", "subseteq", "supset", "supseteq", "cup", "cap",
            "forall", "exists", "emptyset", "mathbb", "mathcal", "mathfrak",
            "vec", "hat", "bar", "overline", "underline", "dot", "ddot",
            "tilde", "widehat", "widetilde", "begin", "end",
            "alpha", "beta", "gamma", "delta", "epsilon", "phi", "theta",
            "omega", "mu", "nu", "pi", "rho", "sigma", "tau", "chi", "psi",
        ]
        functions = ["exp", "sin", "cos", "tan", "log", "ln", "lim"]
        # Match commands followed by non-letters (like \lambda_L or \frac{...})
        command_alt = "|".join(re.escape(cmd) for cmd in commands)
        protected = []

        def protect_text_command(match):
            protected.append(match.group(0))
            return f"@@AI_HINTS_LATEX_TEXT_{len(protected) - 1}@@"

        span = re.sub(
            r'\\(?:text|mathrm|operatorname)\{[^{}]*\}',
            protect_text_command,
            span,
        )
        span = self._unwrap_math_delimiters_inside_span(span)
        span = self._normalize_latex_operators(span)

        # Collapse multiple backslashes before commands (e.g., \\lambda -> \lambda)
        # We check for a non-letter boundary to handle things like \lambda_L correctly.
        span = re.sub(rf'\\{{2,}}(?=(?:{command_alt})(?:[^a-zA-Z]|$))', lambda _m: "\\", span)
        for func in functions:
            span = re.sub(
                rf'\\{func}left(?=\s*\()',
                lambda _m, f=func: "\\" + f + r"\left",
                span,
            )
            span = re.sub(
                rf'(^|[^\\A-Za-z]){func}left(?=\s*\()',
                lambda m, f=func: m.group(1) + "\\" + f + r"\left",
                span,
            )

        for cmd in commands:
            span = re.sub(
                rf'(^|[^\\A-Za-z])({cmd})(?=(_|\b|[{{}}\[\]()+\-=/^*,]))',
                lambda m: m.group(1) + "\\" + m.group(2),
                span,
            )
        span = self._normalize_parenthesized_scripts(span)
        for idx, value in enumerate(protected):
            span = span.replace(f"@@AI_HINTS_LATEX_TEXT_{idx}@@", value)
        return span

    def _normalize_latex_operators(self, span: str) -> str:
        span = re.sub(r'(?<!\\)<->', r'\\leftrightarrow ', span)
        span = re.sub(r'(?<!\\)->', r'\\to ', span)
        span = re.sub(r'(?<!\\)<=', r'\\le ', span)
        span = re.sub(r'(?<!\\)>=', r'\\ge ', span)
        return re.sub(r'(?<!\\)!=', r'\\ne ', span)

    def _normalize_parenthesized_scripts(self, span: str) -> str:
        result = []
        i = 0
        while i < len(span):
            if span[i] in "^_" and i + 1 < len(span) and span[i + 1] == "(":
                end = self._find_matching_paren(span, i + 1)
                if end != -1:
                    inner = span[i + 2:end].strip()
                    if self._looks_like_script_group(inner):
                        result.append(span[i])
                        result.append("{")
                        result.append(inner)
                        result.append("}")
                        i = end + 1
                        continue
            result.append(span[i])
            i += 1
        return "".join(result)

    def _looks_like_script_group(self, text: str) -> bool:
        stripped = text.strip()
        if not stripped or len(stripped) > 120:
            return False
        return bool(re.search(r'[\\A-Za-z0-9+\-*/=^_{}<>]', stripped))

    def _unwrap_math_delimiters_inside_span(self, span: str) -> str:
        span = re.sub(r'\\\((.*?)\\\)', lambda m: m.group(1).strip(), span, flags=re.DOTALL)
        return re.sub(r'\\\[(.*?)\\\]', lambda m: m.group(1).strip(), span, flags=re.DOTALL)

    def _wrap_parenthetical_math(self, text: str) -> str:
        parts = []
        last = 0
        for match in self._MATH_BLOCK_RE.finditer(text):
            parts.append(self._wrap_parenthetical_math_plain(text[last:match.start()]))
            parts.append(match.group(0))
            last = match.end()
        parts.append(self._wrap_parenthetical_math_plain(text[last:]))
        return "".join(parts)

    def _wrap_parenthetical_math_plain(self, text: str) -> str:
        result = []
        i = 0
        while i < len(text):
            if text[i] != "(" or self._is_escaped(text, i):
                result.append(text[i])
                i += 1
                continue

            end = self._find_matching_paren(text, i)
            if end == -1:
                result.append(text[i])
                i += 1
                continue

            if i > 0 and re.match(r'[A-Za-z]', text[i - 1]):
                result.append(text[i:end + 1])
                i = end + 1
                continue

            inner = text[i + 1:end]
            if self._looks_like_math_span(inner) or re.fullmatch(r'\s*[A-Za-z]\s*', inner):
                result.append(r'\(')
                result.append(self._fix_latex_span(inner))
                result.append(r'\)')
            else:
                result.append(text[i:end + 1])
            i = end + 1
        return "".join(result)

    def _wrap_bare_math_tokens(self, text: str) -> str:
        parts = []
        last = 0
        for match in self._MATH_BLOCK_RE.finditer(text):
            parts.append(self._wrap_bare_math_tokens_plain(text[last:match.start()]))
            parts.append(match.group(0))
            last = match.end()
        parts.append(self._wrap_bare_math_tokens_plain(text[last:]))
        return "".join(parts)

    def _wrap_bare_math_tokens_plain(self, text: str) -> str:
        greek = "lambda|alpha|beta|gamma|delta|epsilon|phi|theta|omega"

        text = re.sub(
            r'(?<![\\A-Za-z0-9])([A-Za-z])\(([A-Za-z0-9_,+\-*/^ ]{1,40})\)',
            lambda m: r'\(' + self._fix_latex_span(f"{m.group(1)}({m.group(2)})") + r'\)',
            text,
        )
        text = re.sub(
            rf'(?<![A-Za-z0-9])(\\(?:{greek})_[A-Za-z0-9]+)(?![A-Za-z0-9])',
            lambda m: r'\( ' + self._fix_latex_span(m.group(1)) + r' \)',
            text,
            flags=re.IGNORECASE,
        )
        return re.sub(
            rf'(?<![\\A-Za-z0-9])((?:{greek}|[A-Za-z])_[A-Za-z0-9]+)(?![A-Za-z0-9])',
            lambda m: r'\( ' + self._fix_latex_span(m.group(1)) + r' \)',
            text,
            flags=re.IGNORECASE,
        )

    def _find_matching_paren(self, text: str, start: int) -> int:
        depth = 0
        for idx in range(start, len(text)):
            if self._is_escaped(text, idx):
                continue
            if text[idx] == "(":
                depth += 1
            elif text[idx] == ")":
                depth -= 1
                if depth == 0:
                    return idx
        return -1

    def _is_escaped(self, text: str, index: int) -> bool:
        slashes = 0
        pos = index - 1
        while pos >= 0 and text[pos] == "\\":
            slashes += 1
            pos -= 1
        return slashes % 2 == 1

    def _looks_like_math_span(self, text: str) -> bool:
        stripped = text.strip()
        if not stripped or len(stripped) > 220:
            return False
        return bool(
            re.search(r'[\\_=^{}]', stripped)
            or re.search(r'\b[A-Za-z]+\s*\([^)]*\)', stripped)
        )

    def _should_wrap_standalone_math(self, text: str) -> bool:
        stripped = text.strip()
        if (
            not stripped
            or len(stripped) > 200
            or re.search(r'\\[\(\[]|<anki-mathjax', stripped, flags=re.IGNORECASE)
            or not self._looks_like_math_span(stripped)
        ):
            return False
        if " " in stripped and not re.search(r'[=\\]', stripped):
            return False
        prose_probe = re.sub(r'\\[A-Za-z]+(?:_[A-Za-z0-9]+)?', ' ', stripped)
        prose_probe = re.sub(
            r'\b(?:exp|lambda|frac|left|right|sin|cos|tan|sqrt|log|ln|approx|cdot|partial|alpha|beta|gamma|delta|epsilon|phi|theta|omega)(?:_[A-Za-z0-9]+)?\b',
            ' ',
            prose_probe,
            flags=re.IGNORECASE,
        )
        prose_probe = re.sub(r'\b[A-Za-z]_[A-Za-z0-9]+\b', ' ', prose_probe)
        prose_probe = re.sub(r'\b[A-Za-z]\b', ' ', prose_probe)
        prose_words = re.findall(r'\b[A-Za-z]{2,}\b', prose_probe)
        return len(prose_words) <= 1

    def _convert_to_mathjax_tags(self, text: str) -> str:
        r"""Converts standard LaTeX delimiters \( \) and \[ \] to Anki's <anki-mathjax> tags."""
        if not isinstance(text, str):
            return text

        text = self._normalize_math_text(text)
        
        # Replace \( ... \) and \[ ... \] with <anki-mathjax> ... </anki-mathjax>
        text = re.sub(r'\\\((.*?)\\\)', r'<anki-mathjax>\1</anki-mathjax>', text, flags=re.DOTALL)
        text = re.sub(r'\\\[(.*?)\\\]', r'<anki-mathjax>\1</anki-mathjax>', text, flags=re.DOTALL)
        return text

    def get_note_content(self, note, card=None) -> Tuple[str, str]:
        """Extracts front and back content for AI context based on note type config."""
        model_name = note.model()["name"]
        field_names = self.note_type_fields.get(model_name)
        
        if field_names:
            # Use specific fields from config
            content_parts = []
            for f_name in field_names:
                if f_name in note:
                    content_parts.append(note[f_name])
            content = " ".join(content_parts)
            if "cloze" in model_name.lower():
                content, back = self._focus_current_cloze(content, card)
                return self._clean_html(content), self._clean_html(back)
            return self._clean_html(content), ""
        
        # Fallback to default heuristic
        fields = note.items()
        fields = list(fields)
        front = ""
        back = ""
        
        if fields:
            front = fields[0][1]
            # If it's a Cloze card, we often don't need the other fields for generating options
            if "cloze" in model_name.lower():
                front, back = self._focus_current_cloze(front, card)
            else:
                back = "\n".join([v for k, v in fields[1:]])
        
        return self._clean_html(front), self._clean_html(back)

    def _clean_html(self, html: str) -> str:
        """Remove most HTML tags to reduce tokens and noise."""
        # Remove scripts and styles
        html = re.sub(r"<(script|style).*?>.*?</\1>", "", html, flags=re.DOTALL | re.IGNORECASE)
        # Remove all other tags but keep content
        text = re.sub(r"<.*?>", " ", html)
        # Clean up whitespace
        text = re.sub(r"\s+", " ", text).strip()
        return text

    def _focus_current_cloze(self, text: str, card=None) -> str:
        """Mark the cloze deletion for the current card so the AI targets only it."""
        cloze_number = self._card_ord(card)
        if cloze_number is None:
            return text
        cloze_number += 1

        def replace_cloze(match):
            number = int(match.group(1))
            answer = match.group(2)
            hint = match.group(3) or ""
            if number != cloze_number:
                return answer

            current = f"Current cloze deletion: {answer}"
            if hint:
                current += f" (existing hint: {hint})"
            return current

        return re.sub(r"\{\{c(\d+)::(.*?)(?:::([^{}]*?))?\}\}", replace_cloze, text, flags=re.DOTALL)

    def update_note_with_hints(self, note, data: Dict[str, List[str]], toggles: Dict[str, bool] = None, card=None) -> bool:
        """Appends or replaces the AI hints block in the target field."""
        if not data or (not data.get("hints") and not data.get("options")):
            return False

        data = self.normalize_hint_data(data)

        content_block = self.build_hints_block(data, toggles, card)
        
        # Find target field
        field_name = self._find_target_field(note)
        if not field_name:
            # Fallback to last field if no target found
            field_name = list(note.keys())[-1]

        current_val = note[field_name]
        
        new_val = self._replace_or_append_block(current_val, content_block, card)

        note[field_name] = new_val
        return True

    def build_hints_block(self, data: Dict[str, List[str]], toggles: Dict[str, bool] = None, card=None) -> str:
        """Build the persisted/injected hints block for the configured storage mode."""
        data = self.normalize_hint_data(data)
        attrs = self._build_attrs(toggles, card)
        if self.storage_mode == "json":
            payload = html.escape(json.dumps(data), quote=False)
            return f'<div class="{self.json_class}" {attrs} style="display:none">{payload}</div>'
        return self._build_html_block(data, attrs)

    def _find_target_field(self, note) -> Optional[str]:
        note_fields = note.keys()
        for target in self.target_fields:
            if target in note_fields:
                return target
        return None

    def _build_attrs(self, toggles: Dict[str, bool] = None, card=None) -> str:
        attrs = []
        if toggles:
            attrs.extend([
                f'data-show-hints="{str(toggles.get("show_hints_button", True)).lower()}"',
                f'data-show-options="{str(toggles.get("show_options_button", True)).lower()}"',
            ])

        card_id = self._card_attr(card, "id")
        card_ord = self._card_ord(card)
        if card_id:
            attrs.append(f'data-ai-hints-card-id="{html.escape(card_id, quote=True)}"')
        if card_ord is not None:
            attrs.append(f'data-ai-hints-card-ord="{card_ord}"')
        return " ".join(attrs)

    def _card_attr(self, card, attr: str) -> str:
        if card is None:
            return ""
        value = getattr(card, attr, "")
        if callable(value):
            return ""
        text = str(value).strip()
        if not text or text.startswith("<"):
            return ""
        return text

    def _card_ord(self, card) -> Optional[int]:
        if card is None:
            return None
        value = getattr(card, "ord", None)
        if isinstance(value, bool):
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, str) and value.strip().isdigit():
            return int(value.strip())
        return None

    def find_hints_block(self, note, card=None) -> Optional[str]:
        """Searches all fields of the note for an AI hints block matching the card."""
        pattern = re.compile(
            rf'<div\b[^>]*class=["\'][^"\']*(?:{self.json_class}|{self.container_class})[^"\']*["\'][^>]*>.*?</div>',
            flags=re.DOTALL | re.IGNORECASE,
        )
        for f_val in note.values():
            if not isinstance(f_val, str):
                continue
            for match in pattern.finditer(f_val):
                block = match.group(0)
                if self._block_matches_card(block, card):
                    return block
        return None

    def clear_hints_from_note(self, note, card=None) -> bool:
        """Removes AI hints blocks matching the card from all fields."""
        pattern = re.compile(
            rf'<div\b[^>]*class=["\'][^"\']*(?:{self.json_class}|{self.container_class})[^"\']*["\'][^>]*>.*?</div>',
            flags=re.DOTALL | re.IGNORECASE,
        )
        cleared = False
        for f_name in note.keys():
            current_val = note[f_name]
            if not isinstance(current_val, str):
                continue
            
            new_val = current_val
            field_cleared = False
            matches = list(pattern.finditer(current_val))
            # Work backwards to avoid offset issues
            for match in reversed(matches):
                if self._block_matches_card(match.group(0), card):
                    new_val = new_val[:match.start()] + new_val[match.end():]
                    field_cleared = True
            
            if field_cleared:
                note[f_name] = new_val
                cleared = True
        
        return cleared

    def _replace_or_append_block(self, current_val: str, content_block: str, card=None) -> str:
        pattern = re.compile(
            rf'<div\b[^>]*class=["\'][^"\']*(?:{self.json_class}|{self.container_class})[^"\']*["\'][^>]*>.*?</div>',
            flags=re.DOTALL | re.IGNORECASE,
        )
        matches = list(pattern.finditer(current_val))
        if not matches:
            return current_val + "\n" + content_block

        for match in matches:
            if self._block_matches_card(match.group(0), card):
                return current_val[:match.start()] + content_block + current_val[match.end():]

        for match in matches:
            if not self._block_has_card_scope(match.group(0)):
                return current_val[:match.start()] + content_block + current_val[match.end():]

        return current_val + "\n" + content_block

    def _block_matches_card(self, block: str, card=None) -> bool:
        card_id = self._card_attr(card, "id")
        card_ord = self._card_ord(card)

        block_id = self._data_attr(block, "data-ai-hints-card-id")
        if card_id and block_id:
            return card_id == block_id

        block_ord = self._data_attr(block, "data-ai-hints-card-ord")
        if card_ord is not None and block_ord:
            return str(card_ord) == block_ord

        return not card_id and card_ord is None and not self._block_has_card_scope(block)

    def _block_has_card_scope(self, block: str) -> bool:
        return bool(
            self._data_attr(block, "data-ai-hints-card-id")
            or self._data_attr(block, "data-ai-hints-card-ord")
        )

    def _data_attr(self, block: str, name: str) -> str:
        match = re.search(rf'{name}=["\']([^"\']*)["\']', block)
        return html.unescape(match.group(1)) if match else ""

    def _build_html_block(self, data: Dict[str, List[str]], attrs: str = "") -> str:
        hints = data.get("hints", [])
        options = data.get("options", [])
        
        hints_html = ""
        if hints:
            items = "".join([f"<li>{self._safe_hint_item_html(h)}</li>" for h in hints])
            hints_html = f'<b>AI Hints:</b><br><ul class="ai-hints-hint-list">{items}</ul>'
            
        options_html = ""
        if options:
            items = "".join([f"<li>{self._safe_hint_item_html(o)}</li>" for o in options])
            options_html = f'<b>AI Options:</b><br><ul class="ai-hints-list">{items}</ul>'
            
        return f"""
<div class="{self.container_class}" {attrs}>
    <hr>
    {hints_html}
    {options_html}
</div>
"""

    def _safe_hint_item_html(self, value) -> str:
        escaped = html.escape(str(value), quote=True)
        escaped = re.sub(r'&lt;(anki-mathjax)&gt;', r'<\1>', escaped, flags=re.IGNORECASE)
        escaped = re.sub(r'&lt;/(anki-mathjax)&gt;', r'</\1>', escaped, flags=re.IGNORECASE)
        return escaped
